"""
Menú Sushi Seven - La Paz
Precios de domicilio
"""

MENU = {
    "entradas": [
        {"nombre": "Edamames Salt o Spicy", "desc": "Vaina de soya tierna al vapor. 150g", "precio": 158},
        {"nombre": "Jalapeños Especiales", "desc": "Rellenos de queso crema con cangrejo, mayo roca, salsa de anguila. 9 piezas", "precio": 163},
        {"nombre": "Camarones Roca", "desc": "Salteados con aderezo roca sobre fideo de arroz crujiente. 130g", "precio": 247},
        {"nombre": "Gyozas", "desc": "Rellenas de carne de cerdo con vegetales, salsa especial. 5 piezas", "precio": 173},
        {"nombre": "Tacos de Jícama", "desc": "Camarón empanizado, pico de gallo con mango, chipotle mayo. 3 piezas", "precio": 198},
        {"nombre": "Tamborcitos de Atún", "desc": "Finas láminas, arroz shari y rib eye, salsa teriyaki. 160g", "precio": 256},
        {"nombre": "Kushiages de Queso", "desc": "Queso gouda empanizado. 3 piezas", "precio": 146},
        {"nombre": "Kushiages de Plátano", "desc": "Empanizado, salsa kushiage. 2 piezas", "precio": 68},
        {"nombre": "Kushiages de Camarón y Queso", "desc": "Camarón envuelto con queso crema empanizado. 2 piezas", "precio": 125},
        {"nombre": "Crispy Rice", "desc": "Atún o salmón spicy sobre arroz crujiente. 5 piezas", "precio": 215},
        {"nombre": "Lotus Buns de Short Rib", "desc": "Costilla horneada 24h, mayonesa de trufa. 2 piezas", "precio": 173},
        {"nombre": "Taco de Rib Eye", "desc": "Salsa de ajonjolí, cebolla morada, mayo habanero. 10 piezas", "precio": 335},
        {"nombre": "Tostadas de Atún", "desc": "Won ton crujiente, tartar de atún, aguacate, mayo roca. 3 piezas", "precio": 208},
        {"nombre": "James Tower", "desc": "Salmón, atún o cangrejo picante (a elegir). 200g", "precio": 240},
        {"nombre": "Tempura Dinner", "desc": "Camarón y vegetales tempura, salsa de soya dulce. 200g", "precio": 198},
        {"nombre": "Sunomono Mix", "desc": "Ensalada seaweed, pepino sunomono, aceite de ajonjolí. 150g", "precio": 93},
        {"nombre": "Tacos de Lechuga Cantones", "desc": "Mix de vegetales asiáticos, pollo, salsa de soya dulce. 120g", "precio": 198},
    ],
    "hand_rolls": [
        {"nombre": "Atún", "desc": "Hand roll de atún. 1 pieza", "precio": 104},
        {"nombre": "Salmón", "desc": "Hand roll de salmón. 1 pieza", "precio": 104},
        {"nombre": "Anguila", "desc": "Hand roll de anguila. 1 pieza", "precio": 104},
        {"nombre": "Hamachi Especial", "desc": "Hand roll de hamachi. 1 pieza", "precio": 104},
        {"nombre": "Spicy Crab", "desc": "Hand roll de cangrejo picante. 1 pieza", "precio": 104},
        {"nombre": "Seven", "desc": "Hand roll Seven. 1 pieza", "precio": 104},
    ],
    "temakis": [
        {"nombre": "Atún", "desc": "Temaki de atún. 1 pieza 40g", "precio": 177},
        {"nombre": "Salmón", "desc": "Temaki de salmón. 1 pieza 40g", "precio": 177},
        {"nombre": "Anguila", "desc": "Temaki de anguila. 1 pieza 40g", "precio": 177},
        {"nombre": "Hamachi Especial", "desc": "Temaki de hamachi. 1 pieza 40g", "precio": 177},
        {"nombre": "Spicy Crab", "desc": "Temaki de cangrejo picante. 1 pieza 40g", "precio": 177},
        {"nombre": "Seven", "desc": "Temaki Seven. 1 pieza 40g", "precio": 177},
    ],
    "nigiris": [
        {"nombre": "Atún", "desc": "Nigiri de atún. 1 pieza 12g", "precio": 58},
        {"nombre": "Salmón", "desc": "Nigiri de salmón. 1 pieza 12g", "precio": 62},
        {"nombre": "Camarón", "desc": "Nigiri de camarón. 1 pieza 12g", "precio": 47},
        {"nombre": "Ikura", "desc": "Nigiri de ikura. 1 pieza 12g", "precio": 104},
        {"nombre": "Anguila", "desc": "Nigiri de anguila. 1 pieza 12g", "precio": 68},
        {"nombre": "Hamachi", "desc": "Nigiri de hamachi. 1 pieza 12g", "precio": 72},
        {"nombre": "Sampler", "desc": "Atún, salmón, camarón, anguila. 4 piezas", "precio": 221},
    ],
    "sashimis": [
        {"nombre": "Atún", "desc": "Sashimi de atún. 110g", "precio": 236},
        {"nombre": "Salmón", "desc": "Sashimi de salmón. 110g", "precio": 314},
        {"nombre": "Hamachi", "desc": "Sashimi de hamachi. 100g", "precio": 362},
        {"nombre": "Sampler", "desc": "Atún, Salmón, Hamachi, Ikura. 150g", "precio": 419},
    ],
    "awesome_rolls": [
        {"nombre": "Unagi Roll", "desc": "Aguacate, kanikama tempura / Anguila horneada, ajonjolí", "precio": 278},
        {"nombre": "Kanikama Roll", "desc": "Pescado tempura, aguacate, pepino / Atún, kanikama spicy", "precio": 251},
        {"nombre": "Omatsuri Roll", "desc": "Camarón tempura, kanikama, pepino / Aguacate", "precio": 236},
        {"nombre": "Rock & Roll", "desc": "Aguacate, pepino, pasta de cangrejo / Masago, camarones roca", "precio": 251},
        {"nombre": "San Antonio Roll", "desc": "Tempura de pescado y camarón / Ensalada de cangrejo, aguacate", "precio": 236},
        {"nombre": "Friday Roll", "desc": "Kushiage de camarón con queso crema / Aguacate", "precio": 226},
        {"nombre": "Bora Bora Roll", "desc": "Aguacate, pepino, tempura de camarón / Cangrejo", "precio": 209},
        {"nombre": "Caterpillar Roll", "desc": "Anguila, pepino, queso crema / Aguacate", "precio": 230},
        {"nombre": "Luis Roll", "desc": "Atún picante y aguacate / Salmón", "precio": 268},
        {"nombre": "Chef Especial", "desc": "Camarón, kanikama, aguacate / Salmón fresco e ikura ⭐", "precio": 299},
        {"nombre": "Monkey Roll", "desc": "Queso crema, espárragos, aguacate, camarón tempura / Plátano frito", "precio": 184},
        {"nombre": "Baked Salmon Roll", "desc": "Camarón tempura, espárrago / Salmón horneado, masago ⭐", "precio": 299},
        {"nombre": "Habanero Roll", "desc": "Camarón picante, cilantro, aguacate / Masago, hamachi", "precio": 303},
        {"nombre": "Lomas Roll", "desc": "Camarón tempura, aguacate y coco / Pasta de cangrejo y mango ⭐", "precio": 236},
        {"nombre": "Himalayan Roll", "desc": "Kanikama, queso crema, zanahoria tempura, chiles toreados", "precio": 194},
        {"nombre": "Sonterrey Roll", "desc": "Kanikama, cebollín, aguacate / Queso manchego, chiles toreados ⭐", "precio": 198},
        {"nombre": "Tropical Roll", "desc": "Espárrago, atún, pepino / Salmón, mango ⭐", "precio": 237},
        {"nombre": "Quintana Roll", "desc": "Tartar de atún, camarón tempura / Aguacate, salsa anguila", "precio": 221},
        {"nombre": "Solesta Roll", "desc": "Mango, pasta de cangrejo, aguacate / Salmón, salsa natsu ⭐", "precio": 278},
    ],
    "rollos_ligeros": [
        {"nombre": "Philadelphia Roll", "desc": "Queso crema, salmón ahumado, aguacate, pepino", "precio": 184},
        {"nombre": "Philadelphia Roll Especial", "desc": "Queso crema, salmón ahumado, aguacate, pepino / Masago", "precio": 198},
        {"nombre": "California Roll", "desc": "Aguacate, pepino, kanikama", "precio": 184},
        {"nombre": "California Roll Especial", "desc": "Aguacate, pepino, kanikama / Masago", "precio": 199},
        {"nombre": "Spicy Tuna Roll", "desc": "Mezcla de atún, cebollín, aguacate, mayo picante ⭐", "precio": 205},
        {"nombre": "Ocean Roll", "desc": "Pasta de cangrejo, cebollín / Salmón, atún, camarón, aguacate", "precio": 240},
        {"nombre": "Querétaro Roll", "desc": "Pasta de cangrejo, aguacate / Salmón, atún, masago", "precio": 261},
        {"nombre": "Dinamita Roll", "desc": "Kanikama, queso crema, aguacate, mayo picante / Alga", "precio": 184},
        {"nombre": "Quanza Roll", "desc": "Salmón, cebollín, mayo picante, aguacate ⭐", "precio": 209},
        {"nombre": "Rainbow Roll", "desc": "Aguacate, kanikama, pepino / Salmón, camarón, atún, hamachi", "precio": 251},
        {"nombre": "Mango Roll", "desc": "Espárragos, aguacate, zanahoria, pepino, queso crema / Mango", "precio": 194},
        {"nombre": "Hiko Roll", "desc": "Kanikama picante, aguacate, cebollín / Pepino, salmón. 7 piezas", "precio": 299},
        {"nombre": "La Paz Roll", "desc": "Tilapia, queso crema, cilantro, aguacate / Salmón, chipotle", "precio": 221},
    ],
    "empanizados": [
        {"nombre": "Crispy Roll", "desc": "Queso crema, aguacate, kanikama / Tempurizado, mayo roca", "precio": 173},
        {"nombre": "Kushiage Roll", "desc": "Camarón empanizado, aguacate / Queso crema, tampico", "precio": 221},
        {"nombre": "Texan Roll", "desc": "Aguacate, espárragos, queso crema / Filete empanizado", "precio": 205},
        {"nombre": "Black Panther Roll", "desc": "Pasta de cangrejo, queso crema, aguacate / Alga empanizada", "precio": 221},
        {"nombre": "Sushi Seven Roll", "desc": "Queso crema, camarón empanizado / Tempura, aguacate, tampico ⭐", "precio": 236},
        {"nombre": "Juriky Roll", "desc": "Pescado tempura, queso manchego, aguacate / Nuez, almendra ⭐", "precio": 205},
    ],
    "bowls": [
        {"nombre": "Miso Shiro", "desc": "Sopa de pasta de frijol de soya con tofu, cebollín y wakame. 180ml", "precio": 83},
        {"nombre": "Sopa de Mariscos con Udon", "desc": "Salmón, camarón, kanikama, callo de almeja, udon. 300ml", "precio": 208},
        {"nombre": "Tokyo Ramen", "desc": "Sopa japonesa, pork belly, naruto, huevo marinado. 300ml", "precio": 208},
        {"nombre": "Steak Ramen", "desc": "Rib eye, fondo de res, huevo marinado, cebollín. 300ml", "precio": 208},
        {"nombre": "Beijing Chicken", "desc": "Pollo tempurizado con salsa de naranja y arroz gohan. 120g", "precio": 219},
        {"nombre": "Kung Pao Shrimp", "desc": "Camarón con vegetales, salsa dulce y picante, arroz gohan. 180g", "precio": 240},
        {"nombre": "Yaki Udon Mixto", "desc": "Camarón, pollo y filete, mix de vegetales. 250g", "precio": 230},
        {"nombre": "Lo Mein Mixto", "desc": "Tallarín ramen, camarón, pollo, filete, vegetales. 250g", "precio": 230},
        {"nombre": "Teppanyaki Mixto", "desc": "Camarón, filete de res, pollo y vegetales. 300g", "precio": 326},
        {"nombre": "Poke Bowl Rainbow", "desc": "Arroz sushi, hamachi, atún, salmón, aguacate. 200g", "precio": 251},
        {"nombre": "Poke Bowl Dinamita", "desc": "Arroz, camarón roca, queso crema, kanikama, aguacate. 220g", "precio": 209},
        {"nombre": "Poke Bowl Crispy Salmón", "desc": "Arroz, salmón, aguacate, pepino, tempura crunch. 220g", "precio": 209},
        {"nombre": "Bowl de Salmón", "desc": "Salmón parrillado, yakimeshi, vegetales, teriyaki. 200g", "precio": 278},
        {"nombre": "Bowl de Filete de Res", "desc": "Filete parrillado, yakimeshi, vegetales, yuzu soy. 200g", "precio": 261},
        {"nombre": "Bowl de Camarón", "desc": "Camarón parrillado, yakimeshi, vegetales. 200g", "precio": 240},
        {"nombre": "Bowl de Pollo", "desc": "Pollo parrillado, yakimeshi, vegetales, teriyaki. 200g", "precio": 215},
        {"nombre": "Bowl de Vegetales", "desc": "Vegetales parrillados con mantequilla de ajo. 220g", "precio": 125},
    ],
    "yakimeshi": [
        {"nombre": "Yakimeshi Mixto", "desc": "Arroz frito mixto. 220g", "precio": 173},
        {"nombre": "Yakimeshi Carne", "desc": "Arroz frito con carne. 220g", "precio": 173},
        {"nombre": "Yakimeshi Camarón", "desc": "Arroz frito con camarón. 220g", "precio": 173},
        {"nombre": "Yakimeshi Pollo", "desc": "Arroz frito con pollo. 220g", "precio": 152},
        {"nombre": "Yakimeshi Vegetales", "desc": "Arroz frito con vegetales. 220g", "precio": 93},
        {"nombre": "Gohan", "desc": "Arroz blanco. 140g", "precio": 51},
    ],
    "postres": [
        {"nombre": "Chocolate Lava Cake", "desc": "Helado de vainilla, cocoa y frutos rojos. 110g", "precio": 163},
        {"nombre": "Skillet Nutella Cookie", "desc": "Masa de galleta con nutella y helado de plátano. 200g", "precio": 205},
        {"nombre": "Helado de Tempura", "desc": "8 piezas", "precio": 175},
        {"nombre": "Banoffee", "desc": "Pay cremoso de vainilla, plátano, nuez caramelizada. 240g", "precio": 194},
        {"nombre": "Tempura Oreo", "desc": "10 piezas", "precio": 142},
        {"nombre": "Mochis", "desc": "Pastelito de arroz relleno de helado. 3 piezas", "precio": 198},
        {"nombre": "Mochi Pieza", "desc": "Chocolate, fresa, matcha o mango. 1 pieza", "precio": 69},
        {"nombre": "Cheesecake de Frutos Rojos", "desc": "NY Style con compota de frutos rojos. 200g", "precio": 194},
    ],
    "bebidas": [
        {"nombre": "Agua Natural Ciel", "desc": "600ml", "precio": 58},
        {"nombre": "Agua Mineral Peñafiel", "desc": "355ml", "precio": 58},
        {"nombre": "Agua Mineral Topochico", "desc": "355ml", "precio": 73},
        {"nombre": "Agua Mineral Perrier", "desc": "330ml", "precio": 82},
        {"nombre": "Calpis Natural o Mineral", "desc": "230ml", "precio": 75},
        {"nombre": "Calpis de Sabores", "desc": "Blueberry, Fresa, Jamaica, Mango, Maracuyá, Tamarindo", "precio": 79},
        {"nombre": "Coca Cola Clásica", "desc": "355ml", "precio": 58},
        {"nombre": "Coca Cola Light", "desc": "355ml", "precio": 58},
        {"nombre": "Coca Cola Zero", "desc": "355ml", "precio": 58},
        {"nombre": "Sprite", "desc": "355ml", "precio": 58},
        {"nombre": "Fanta", "desc": "355ml", "precio": 58},
        {"nombre": "Sidral", "desc": "355ml", "precio": 58},
        {"nombre": "Velvet Soda Lychee", "desc": "275ml", "precio": 83},
        {"nombre": "Ginger Ale", "desc": "355ml", "precio": 58},
        {"nombre": "Heineken", "desc": "355ml", "precio": 84},
        {"nombre": "Heineken 0.0", "desc": "250ml", "precio": 84},
        {"nombre": "Sapporo Premium", "desc": "473ml", "precio": 147},
        {"nombre": "Stella Artois", "desc": "330ml", "precio": 84},
        {"nombre": "Ultra Michelob", "desc": "355ml", "precio": 84},
    ],
    "extras": [
        {"nombre": "Aguacate Extra", "desc": "30g", "precio": 25},
        {"nombre": "Mayo Chipotle Extra", "desc": "60ml", "precio": 19},
        {"nombre": "Mayo Roca Extra", "desc": "60ml", "precio": 19},
        {"nombre": "Queso Crema Extra", "desc": "30g", "precio": 32},
        {"nombre": "Salsa de Anguila Extra", "desc": "60ml", "precio": 19},
        {"nombre": "Tampico Extra", "desc": "60ml", "precio": 32},
        {"nombre": "Salsa Sriracha Extra", "desc": "60ml", "precio": 19},
        {"nombre": "Filete de Res Extra", "desc": "40g", "precio": 83},
        {"nombre": "Salmón Extra", "desc": "40g", "precio": 83},
        {"nombre": "Atún Extra", "desc": "30g", "precio": 60},
        {"nombre": "Camarón Extra", "desc": "60g", "precio": 77},
        {"nombre": "Pollo Extra", "desc": "50g", "precio": 48},
    ]
}

CATEGORIAS = {
    "1": ("entradas", "🥗 Entradas"),
    "2": ("hand_rolls", "🌯 Hand Rolls"),
    "3": ("temakis", "🌮 Temakis"),
    "4": ("nigiris", "🍣 Nigiris"),
    "5": ("sashimis", "🐟 Sashimis"),
    "6": ("awesome_rolls", "⭐ Awesome Rolls"),
    "7": ("rollos_ligeros", "🥢 Rollos Ligeros"),
    "8": ("empanizados", "🍤 Empanizados y Capeados"),
    "9": ("bowls", "🍜 Bowls"),
    "10": ("yakimeshi", "🍚 Yakimeshi"),
    "11": ("postres", "🍮 Postres"),
    "12": ("bebidas", "🥤 Bebidas"),
    "13": ("extras", "➕ Extras"),
}

def get_menu_text(categoria_key):
    items = MENU.get(categoria_key, [])
    lines = []
    for i, item in enumerate(items, 1):
        lines.append(f"{i}. *{item['nombre']}* — ${item['precio']}\n   _{item['desc']}_")
    return "\n\n".join(lines)

def get_categorias_text():
    lines = ["🍱 *Menú Sushi Seven - La Paz*\n\n¿Qué quieres ordenar? Elige una categoría:\n"]
    for num, (key, nombre) in CATEGORIAS.items():
        lines.append(f"{num}. {nombre}")
    lines.append("\nEscribe el número de la categoría.")
    return "\n".join(lines)
